# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5b05a831ceca51b4ebc56303f4967de9ac462f1f7916676147cbf4c17964739e065336de078bc27baf6e412c2c17597c97708a2afdf540ff3ca46b4f0e7691c9

test:
  secret_key_base: 9d7d3a8d5931959bac24116e99f145fd0069a030f66ace9f226be0c5c01ef0e5b8a46b2d9ec880fcbec1d29b75d68a566d24aa4268b97ff917de5b68631d4fea

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
